/* GENERATED by packages/cms/tracy-cms-preview/scripts/build.mjs — do not edit.
   The cms-preview gate compares this file byte-for-byte with a fresh build. */

/** The `channel` field every message on the live-preview contract carries. */
export const PREVIEW_CHANNEL = "tracy-preview"

/** The contract version; a page announcing another one is left alone. */
export const PREVIEW_VERSION = 1

/** What a page can be asked to do, cheapest first. */
export const PREVIEW_MODES = ["style","full"] as const

/** The mode used for anything the side card cannot classify. */
export const PREVIEW_DEFAULT_MODE = "full"

/** One mode on the contract. */
export type PreviewMode = (typeof PREVIEW_MODES)[number]

/**
 * One refresh request, as the side card sends it into a page.
 * @param mode - the mode to ask for; an unknown one is sent as the default.
 * @returns the message to post.
 */
export function previewRefreshMessage(mode: string): { channel: string; v: number; kind: string; mode: string } {
  const known = (PREVIEW_MODES as readonly string[]).includes(mode)
  return { channel: PREVIEW_CHANNEL, v: PREVIEW_VERSION, kind: 'refresh', mode: known ? mode : PREVIEW_DEFAULT_MODE }
}

/**
 * Whether a received value is a message on this contract, of one kind.
 *
 * Total and dull on purpose: it is handed whatever a framed page posted, so it assumes nothing
 * about the value and never throws.
 * @param value - the `data` of a received message event.
 * @param kind - the kind the reader is willing to act on.
 * @returns whether the value is that message.
 */
export function isPreviewMessage(value: unknown, kind: string): boolean {
  if (value === null || typeof value !== 'object') return false
  const message = value as { channel?: unknown; v?: unknown; kind?: unknown }
  return message.channel === PREVIEW_CHANNEL && message.v === PREVIEW_VERSION && message.kind === kind
}

/** What a page can do beyond refreshing; a side card lights a feature only when the page names it. */
export const PREVIEW_FEATURES = ["pick","track","reveal","text","hold","scroll","follow","lockstep","name","clip","route","refocus","pins60","wheel"] as const

/** The picker kinds: the side card sends start/stop/level/track/reveal, the page sends hover/picked/cancel/rect/lost/text. */
export const PREVIEW_PICK = {"start":"pick-start","stop":"pick-stop","level":"pick-level","hover":"pick-hover","picked":"picked","cancel":"pick-cancel","track":"pick-track","rect":"pick-rect","lost":"pick-lost","reveal":"pick-reveal","text":"pick-text","hold":"pick-hold","outside":"pick-outside","scroll":"pick-scroll","scrollTo":"pick-scroll-to","step":"pick-step","drawn":"pick-drawn","refocus":"pick-refocus","wheel":"pick-wheel"} as const

/** How much of the page one picked element may carry out. */
export const PREVIEW_PICK_LIMITS = {"text":300,"marks":12,"levels":8,"domPath":8} as const

/** A box in the framed page's viewport, in CSS pixels. */
export interface PreviewPickRect {
  x: number
  y: number
  width: number
  height: number
}

/** One place the pick can move to: the element itself (index 0) or an ancestor carrying a mark. */
export interface PreviewPickLevel {
  tag: string
  mark: string | null
  text: string
  rect: PreviewPickRect
}

/**
 * What a page reports about the element under the pointer or the one picked. `marks` are the
 * provenance stamps the CMS printed, innermost first; which record they mean is the server's
 * answer (`content.locate`), not the page's.
 */
export interface PreviewPickTarget {
  text: string
  /** A container's own words when it has none: its subtree's text, capped (optional, additive). */
  inside?: string
  /** Runtime 14 (`name`): what a person calls an element with no words of its own (optional). */
  name?: string
  /** Runtime 14 (`clip`): why the element must not be drawn over (optional; absent = it can be seen). */
  hidden?: PreviewHidden
  tag: string
  image: { src: string; alt: string } | null
  domPath: string
  selector: string
  rect: PreviewPickRect
  marks: string[]
  levels: PreviewPickLevel[]
  level: number
}

/**
 * One picker request, as the side card sends it into a page.
 * @param kind - start, stop or level; anything else is not a request.
 * @param index - for a level request, which reported level; clamped to a whole number of at least 0.
 * @returns the message to post, or null.
 */
export function previewPickMessage(kind: string, index?: unknown): { channel: string; v: number; kind: string; index?: number } | null {
  if (kind === PREVIEW_PICK.start || kind === PREVIEW_PICK.stop) return { channel: PREVIEW_CHANNEL, v: PREVIEW_VERSION, kind }
  if (kind === PREVIEW_PICK.level) {
    const n = typeof index === 'number' && Number.isFinite(index) ? Math.max(0, Math.floor(index)) : 0
    return { channel: PREVIEW_CHANNEL, v: PREVIEW_VERSION, kind, index: n }
  }
  return null
}

/** The outline colours a tracked element can wear (`pick-track` items). */
export const PREVIEW_TRACK_STATES = ["saved","active","sent","working","done","failed","asked","pending"] as const

/** One tracked element's outline colour. */
export type PreviewTrackState = (typeof PREVIEW_TRACK_STATES)[number]

/** Why a page says a tracked element is gone (`pick-lost`). */
export const PREVIEW_LOST_REASONS = ["missing","many","changed"] as const

/** One reason a tracked element is gone. */
export type PreviewLostReason = (typeof PREVIEW_LOST_REASONS)[number]

/** Why an element the page still finds must not be drawn over (`hidden`, runtime 14 feature `clip`). */
export const PREVIEW_HIDDEN_REASONS = ["clipped","covered"] as const

/** One reason an element must not be drawn over. */
export type PreviewHidden = (typeof PREVIEW_HIDDEN_REASONS)[number]

/** Bounds on `pick-track`; `match` is how many leading characters of `text` must still begin the element. */
export const PREVIEW_TRACK_LIMITS = {"items":60,"itemsBefore16":12,"id":64,"selector":512,"match":40} as const

/** One element the side card asks a page to keep outlined and report (`pick-track`). */
export interface PreviewTrackItem {
  id: string
  selector: string
  text: string
  state: PreviewTrackState
}

/**
 * One `pick-track` request: the WHOLE tracked set, replacing the last one (`[]` tracks nothing).
 * Refuses exactly what the page refuses — a set it would ignore is never sent.
 * @param items - the set to track.
 * @returns the message to post, or null when any item is out of bounds.
 */
export function previewTrackMessage(items: unknown): { channel: string; v: number; kind: string; items: PreviewTrackItem[] } | null {
  if (!Array.isArray(items) || items.length > PREVIEW_TRACK_LIMITS.items) return null
  const out: PreviewTrackItem[] = []
  const ids = new Set<string>()
  for (const item of items as unknown[]) {
    if (item === null || typeof item !== 'object') return null
    const { id, selector, text, state } = item as Record<string, unknown>
    if (typeof id !== 'string' || id === '' || id.length > PREVIEW_TRACK_LIMITS.id || ids.has(id)) return null
    if (typeof selector !== 'string' || selector === '' || selector.length > PREVIEW_TRACK_LIMITS.selector) return null
    if (typeof text !== 'string' || text.length > PREVIEW_PICK_LIMITS.text) return null
    if (typeof state !== 'string' || !(PREVIEW_TRACK_STATES as readonly string[]).includes(state)) return null
    ids.add(id)
    out.push({ id, selector, text, state: state as PreviewTrackState })
  }
  return { channel: PREVIEW_CHANNEL, v: PREVIEW_VERSION, kind: PREVIEW_PICK.track, items: out }
}

/**
 * One `pick-reveal` request: scroll one tracked element into view, flash it, report its rect. Only a
 * page whose `ready` names `reveal` answers it; an id outside the tracked set is ignored.
 * @param id - a tracked item id.
 * @returns the message to post, or null for an id no tracked item could carry.
 */
export function previewRevealMessage(id: unknown): { channel: string; v: number; kind: string; id: string } | null {
  if (typeof id !== 'string' || id === '' || id.length > PREVIEW_TRACK_LIMITS.id) return null
  return { channel: PREVIEW_CHANNEL, v: PREVIEW_VERSION, kind: PREVIEW_PICK.reveal, id }
}

/**
 * `pick-hold {on}` (runtime 11, feature `hold`): while `on`, the page swallows every click and answers
 * `pick-outside {x, y}` instead; the wheel, scrolling and keys pass.
 * @param on - a box is open in the side card.
 */
export function previewHoldMessage(on: boolean): { channel: string; v: number; kind: string; on: boolean } {
  return { channel: PREVIEW_CHANNEL, v: PREVIEW_VERSION, kind: PREVIEW_PICK.hold, on: on === true }
}

/** Where a page is scrolled to, in whole CSS pixels (`pick-scroll`, and what `pick-scroll-to` asks). */
export interface PreviewScroll {
  x: number
  y: number
}

/**
 * One `pick-scroll-to` request: put the page back at a scroll offset. Only a page whose `ready` names
 * `scroll` answers it.
 * @param x - the horizontal offset, CSS pixels.
 * @param y - the vertical offset, CSS pixels.
 * @returns the message to post, or null for a place no page could be scrolled to.
 */
export function previewScrollToMessage(x: unknown, y: unknown): { channel: string; v: number; kind: string; x: number; y: number } | null {
  if (typeof x !== 'number' || typeof y !== 'number' || !Number.isFinite(x) || !Number.isFinite(y)) return null
  if (x < 0 || y < 0) return null
  return { channel: PREVIEW_CHANNEL, v: PREVIEW_VERSION, kind: PREVIEW_PICK.scrollTo, x: Math.round(x), y: Math.round(y) }
}

/**
 * One `pick-wheel` step (runtime 16): the wheel over a side card box, for the box its element sits
 * in. Only a page whose `ready` names `wheel` answers it.
 * @param dx - horizontal step, CSS pixels of the page.
 * @param dy - vertical step.
 * @param id - the tracked item the box belongs to; undefined or null for the open pick.
 * @returns the message to post, or null for a step or an id the page would refuse.
 */
export function previewWheelMessage(dx: unknown, dy: unknown, id?: unknown): { channel: string; v: number; kind: string; dx: number; dy: number; id?: string } | null {
  if (typeof dx !== 'number' || typeof dy !== 'number' || !Number.isFinite(dx) || !Number.isFinite(dy)) return null
  const x = Math.round(dx)
  const y = Math.round(dy)
  if ((x === 0 && y === 0) || Math.abs(x) > 20000 || Math.abs(y) > 20000) return null
  const message = { channel: PREVIEW_CHANNEL, v: PREVIEW_VERSION, kind: PREVIEW_PICK.wheel, dx: x, dy: y }
  if (id === undefined || id === null) return message
  if (typeof id !== 'string' || id === '' || id.length > PREVIEW_TRACK_LIMITS.id) return null
  return { ...message, id }
}
